export default {
  products: [
    {
      _id: '1',
      name: 'Name 1',
      category: 'category 1',
      image: '/images/',
      price: 6,
      brand: 'brand',
      rating: 4.3,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '2',
      name: 'Name 2',
      category: 'category 1',
      image: '/images/',
      price: 6,
      brand: 'brand',
      rating: 4.3,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '3',
      name: 'Name 3',
      category: 'category 1',
      image: '/images/',
      price: 6,
      brand: 'brand',
      rating: 4.3,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '4',
      name: 'Name 4',
      category: 'category 1',
      image: '/images/',
      price: 6,
      brand: 'brand',
      rating: 4.3,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '5',
      name: 'Name 5',
      category: 'category 1',
      image: '/images/',
      price: 6,
      brand: 'brand',
      rating: 4.3,
      numReviews: 10,
      countInStock: 6,
    },
  ],
};
